version: '3'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: database
    volumes:
      - database-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vercel_clone

volumes:
  database-vol:
    driver: local